In [1]:
#!/usr/bin/env python3
"""
Neven Caplar 
Last updated: 2023-10-20

Goals: 
Fit the data

Each Section can/should be able to run independently,
only these initial imports should be shared among all sections

Questions:
What determines memory limit of the workers
How to partition the dataframe in order to get more workers active


"""
import numpy as np
import pandas as pd
import pyarrow as pa

# from scipy.spatial import KDTree
import matplotlib.pyplot as plt

import JaxPeriodDrwFit


from tape.ensemble import Ensemble
from tape.utils import ColumnMapper


from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)
np.set_printoptions(suppress=True)
np.set_printoptions(precision=4)


In [2]:
import dask
# many workers
# dask.config.set(scheduler='threads') 

# does not work
# from multiprocessing.pool import ThreadPool
# dask.config.set(pool=ThreadPool(20))

# one worker
# dask.config.set(scheduler='processes')  
from dask.distributed import Client, LocalCluster
cluster = LocalCluster()
client = Client(cluster)
cluster.adapt(minimum=12, maximum=20) 

In [3]:
ens = Ensemble(client = client)  # initialize an ensemble object
ens.client_info()


<Client: 'tcp://127.0.0.1:42168' processes=8 threads=64, memory=251.68 GiB>

In [4]:
# Tape Single Pixel - real data 

# Tape Single Pixel - real data 

In [4]:
# if running on baldur
data_path = "/astro/store/epyc/data3/hipscat/catalogs/tape_test/"

col_map = ColumnMapper(id_col="SDSS_NAME_dr16q_constant", 
                       time_col="mjd_ztf_source",
                       flux_col="mag_ztf_source", 
                       err_col="magerr_ztf_source",
                       band_col="band_ztf_source")

ens.from_hipscat(data_path,
                 source_subdir="tape_test_sources",
                 object_subdir="tape_test_obj",
                 column_mapper=col_map,
                 additional_cols=True,
                 sync_tables=True)

/astro/users/ncaplar/miniconda3/envs/lf_tape_dev/lib/python3.10/site-packages/dask/dataframe/core.py:5243: UserWarning: New index has same name as existing, this is a no-op.
  warnings.warn(
/astro/users/ncaplar/miniconda3/envs/lf_tape_dev/lib/python3.10/site-packages/dask/dataframe/core.py:5243: UserWarning: New index has same name as existing, this is a no-op.
  warnings.warn(
/astro/users/ncaplar/miniconda3/envs/lf_tape_dev/lib/python3.10/site-packages/dask/dataframe/methods.py:357: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[name] = val
/astro/users/ncaplar/miniconda3/envs/lf_tape_dev/lib/python3.10/site-packages/dask/dataframe/methods.py:357: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` 

In [5]:
ens.query("band_ztf_source == 'g'", table = 'source')
ens._source

Dask DataFrame Structure:
              _hipscat_index PLATE_dr16q_constant MJD_dr16q_constant FIBERID_dr16q_constant RA_dr16q_constant DEC_dr16q_constant OBJID_dr16q_constant IF_BOSS_SDSS_dr16q_constant Z_DR16Q_dr16q_constant SOURCE_Z_DR16Q_dr16q_constant Z_FIT_dr16q_constant Z_SYS_dr16q_constant Z_SYS_ERR_dr16q_constant EBV_dr16q_constant SN_MEDIAN_ALL_dr16q_constant FEII_UV_EW_dr16q_constant FEII_UV_EW_ERR_dr16q_constant FEII_OPT_EW_dr16q_constant FEII_OPT_EW_ERR_dr16q_constant LOGL1350_dr16q_constant LOGL1350_ERR_dr16q_constant LOGL1700_dr16q_constant LOGL1700_ERR_dr16q_constant LOGL2500_dr16q_constant LOGL2500_ERR_dr16q_constant LOGL3000_dr16q_constant LOGL3000_ERR_dr16q_constant LOGL5100_dr16q_constant LOGL5100_ERR_dr16q_constant LOGLBOL_dr16q_constant LOGLBOL_ERR_dr16q_constant LOGMBH_HB_dr16q_constant LOGMBH_HB_ERR_dr16q_constant LOGMBH_MGII_dr16q_constant LOGMBH_MGII_ERR_dr16q_constant LOGMBH_CIV_dr16q_constant LOGMBH_CIV_ERR_dr16q_constant LOGMBH_dr16q_constant LOGMBH_ERR_dr16q_constant LOGLEDD_RATIO_dr16q_constant LOGLEDD_RATIO_ERR_dr16q_constant Norder_dr16q_constant Dir_dr16q_constant Npix_dr16q_constant objID_ps1_otmo surveyID_ps1_otmo objInfoFlag_ps1_otmo qualityFlag_ps1_otmo raMean_ps1_otmo decMean_ps1_otmo raMeanErr_ps1_otmo decMeanErr_ps1_otmo epochMean_ps1_otmo nDetections_ps1_otmo ng_ps1_otmo nr_ps1_otmo ni_ps1_otmo nz_ps1_otmo ny_ps1_otmo gMeanPSFMag_ps1_otmo gMeanPSFMagErr_ps1_otmo gFlags_ps1_otmo rMeanPSFMag_ps1_otmo rMeanPSFMagErr_ps1_otmo rFlags_ps1_otmo iMeanPSFMag_ps1_otmo iMeanPSFMagErr_ps1_otmo iFlags_ps1_otmo zMeanPSFMag_ps1_otmo zMeanPSFMagErr_ps1_otmo zFlags_ps1_otmo yMeanPSFMag_ps1_otmo yMeanPSFMagErr_ps1_otmo yFlags_ps1_otmo Norder_ps1_otmo Dir_ps1_otmo Npix_ps1_otmo    _DIST index_ztf_source ps1_objid_ztf_source ra_ztf_source dec_ztf_source ps1_gMeanPSFMag_ztf_source ps1_rMeanPSFMag_ztf_source ps1_iMeanPSFMag_ztf_source nobs_g_ztf_source nobs_r_ztf_source nobs_i_ztf_source mean_mag_g_ztf_source mean_mag_r_ztf_source mean_mag_i_ztf_source catflags_ztf_source fieldID_ztf_source mag_ztf_source magerr_ztf_source mjd_ztf_source rcID_ztf_source band_ztf_source Norder_ztf_source Dir_ztf_source Npix_ztf_source objID_ps_source uniquePspsP2id_ps_source detectID_ps_source filterID_ps_source obsTime_ps_source ra_ps_source dec_ps_source raErr_ps_source decErr_ps_source zp_ps_source expTime_ps_source psfFlux_ps_source psfFluxErr_ps_source apFlux_ps_source apFluxErr_ps_source kronFlux_ps_source kronFluxErr_ps_source infoFlag_ps_source infoFlag2_ps_source infoFlag3_ps_source Norder_ps_source Dir_ps_source Npix_ps_source           Norder              Dir provenance
npartitions=4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

In [7]:
ens._source = ens._source.repartition(npartitions = 12)

In [6]:
# 9min, 13 sec on baldur, for 603 sources in 4 partitions
# 3min, 3 sec on baldur, with padding 
# 44.5 sec on baldur, with coarse padding and 12 partitions
JaxPeriodDrwFit_instance = JaxPeriodDrwFit.JaxPeriodDrwFit()
res_tsp = ens.batch(JaxPeriodDrwFit_instance.optimize_map, 'mjd_ztf_source', "mag_ztf_source", "magerr_ztf_source",
                compute=True, meta=None, n_init=100, use_pad=False)

900000000
900000000
900000000
900000000


An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.


900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000
900000000


In [ ]:
JaxPeriodDrwFit_instance = JaxPeriodDrwFit.JaxPeriodDrwFit()
res_tsp_slow = ens.batch(JaxPeriodDrwFit_instance.optimize_map, 'mjd_ztf_source', "mag_ztf_source", "magerr_ztf_source",
                compute=True, meta=None, n_init=100, use_pad=False)

In [ ]:
res_tsp_slow

SDSS_NAME_dr16q_constant
024148.63-005335.9    [55.079889173002556, -0.5152657753292795, -5.5...
024213.54-004806.8    [3.8236512119177024, 3.007087859826639, -6.742...
024226.33-005254.9    [62.03996834495848, 0.8416924462789179, -0.748...
024234.93-010351.9    [-23.179110258985446, -14.094885974323425, -6....
024235.93-005836.2    [0.5135939370612809, 2.038876710371427, -9.548...
                                            ...                        
024338.49+004620.5    [1.103571577298907, 0.31779175143016936, -7.54...
024351.44+005106.8    [3.374255701009206, 0.8142596747403237, -4.599...
024400.64+004723.0    [-107.04529034571628, -14.353206037063927, -7....
024415.65+005658.7    [65.64692411476958, 2.0791797044960476, -1.349...
024419.10+005539.2    [-97.45003804976099, 2.6623598432609326, -1.45...
Name: SDSS_NAME_dr16q_constant, Length: 611, dtype: object

In [ ]:
res_tsp_slow[100]

/tmp/ipykernel_13332/3759382784.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  res_tsp_slow[100]


array([ 19.2173, -16.9653,  -6.3153,   2.8854,  -0.5213])

In [ ]:
res_tsp[100]

/tmp/ipykernel_13332/2439287074.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  res_tsp[100]


array([340.1118,   0.7439,  -5.1535,   2.8854,  -0.5213])

In [ ]:
(res_tsp_slow[0] - res_tsp[0])/res_tsp_slow[0]

/tmp/ipykernel_13332/295241668.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  (res_tsp_slow[0] - res_tsp[0])/res_tsp_slow[0]


array([-6.8207,  0.2711,  0.1101, -0.    ,  0.    ])

In [ ]:
JaxPeriodDrwFit_instance = JaxPeriodDrwFit.JaxPeriodDrwFit()
res_tsp_drw = ens.batch(JaxPeriodDrwFit_instance.optimize_map_drw, 'mjd_ztf_source', "mag_ztf_source", "magerr_ztf_source",
                compute=True, meta=None, n_init=100)

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.


In [ ]:
df = pd.DataFrame(columns = ['neg_log_lh','log_drw_scale', 'log_drw_amp', 'log_per_scale', 'log_per_amp'],
                   index = res_tsp.index)
for i in range(len(res_tsp)):
    df.iloc[i] = res_tsp[i]

pa_table = pa.Table.from_pandas(df)
pa.parquet.write_table(pa_table, "/astro/users/ncaplar/data/res_tsp_run_g_0.parquet")

/tmp/ipykernel_86669/1838388558.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[i] = res_tsp[i]


In [ ]:
df_drw = pd.DataFrame(columns = ['neg_log_lh', 'log_drw_scale', 'log_drw_amp'],
                   index = res_tsp_drw.index)

for i in range(len(res_tsp_drw)):
    df_drw.iloc[i] = res_tsp_drw[i]
    
pa_table_drw = pa.Table.from_pandas(df_drw)
pa.parquet.write_table(pa_table_drw, "/astro/users/ncaplar/data/res_tsp_run_g_0_drw.parquet")

/tmp/ipykernel_86669/1680990878.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_drw.iloc[i] = res_tsp_drw[i]
